CREATE TABLE IF NOT EXISTS RANKINGS
(
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    group_code   INTEGER         NOT NULL,
    group_name   TEXT            NOT NULL,
    choreography TEXT            NOT NULL,
    genre        TEXT            NOT NULL,
    sub_genre    TEXT            NOT NULL,
    category     TEXT            NOT NULL,
    score        REAL            NOT NULL,
    result       TEXT            NOT NULL
);

CREATE INDEX IF NOT EXISTS RANKING_GROUP_NAME_IDX ON RANKINGS (group_name);
CREATE INDEX IF NOT EXISTS RANKING_CHOREOGRAPHY_IDX ON RANKINGS (choreography);
CREATE INDEX IF NOT EXISTS RANKING_GENRE_IDX ON RANKINGS (genre);
CREATE INDEX IF NOT EXISTS RANKING_SUB_GENRE_IDX ON RANKINGS (sub_genre);
CREATE INDEX IF NOT EXISTS RANKING_CATEGORY_IDX ON RANKINGS (category);
CREATE INDEX IF NOT EXISTS RANKING_SCORE_IDX ON RANKINGS (score);